version: '3'
services:
  gold-price-service:
    build: ./gold-price-service
    ports:
      - "3001:3001"
    networks:
      - my-network

  forex-price-service:
    build: ./forex-price-service
    ports:
      - "3002:3002"
    networks:
      - my-network

  container-health:
    build: ./container-health
    ports:
      - "6002:6002"
    networks:
      - my-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  server-health:
    build: ./server-health
    ports:
      - "6003:6003"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
