# docker-compose.yml
version: '3'
services:
  gold-price-service:
    build: ./gold-price-service
    ports:
      - "3001:3001"

  forex-price-service:
    build: ./forex-price-service
    ports:
      - "3002:3002"
