services:
  api-health:
    build: ./api-health
    ports:
      - "3001:3001"
    networks:
      - my-network
    
  container-health:
    build: ./container-health
    ports:
      - "3002:3002"
    networks:
      - my-network

  server-health:
    build: ./server-health
    ports:
      - "3003:3003"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
