global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'gold-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['gold-api:5000']

  - job_name: 'forex-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['forex-api:5001']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']